### PR TITLE
Propose License Change to ISC

### PR DESCRIPTION
**Pull request by ax3l**
As part of https://github.com/ComputationalRadiationPhysics/picongpu/issues/586 I moved the cmake modules for maintenance and inclusion in other projects to a own repo.

We will re-add them via `git subtree` to `PIConGPU`.

Doing so, I took the chance to re-license them as under the [ISC license](https://en.wikipedia.org/wiki/ISC_license) which is the preferred choice for simple, new-BSD-like licenses and scripts like that where copyleft is not necessary to support the open source community.

@f-schmitt-zih @psychocoderHPC @slizzered as co-authors of some of the modules - can you please post your `yay` / `nej` to this pull request if you agree / disagree to the license change of your according files?

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
I am fine with this license change.

**Comment by slizzered** [comment]
looks good, go ahead :+1:

**Comment by ax3l** [comment]
@f-schmitt-zih ? :)

**Comment by f-schmitt** [comment]
+1

**Pull request merged**
